services:
  mysql:
    image: mysql:8.0
    container_name: t178-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: t178
      TZ: Asia/Shanghai
    ports:
      - "3311:3306"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_general_ci",
      "--default-time-zone=+08:00"
    ]
    volumes:
      - t178_mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

volumes:
  t178_mysql_data: